# Generated by Django 2.0.2 on 2018-03-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttons', '0002_auto_20180309_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
