# Generated by Django 2.0.2 on 2018-03-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttons', '0005_auto_20180309_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('corp_name', models.CharField(default='', max_length=40)),
                ('corp_code', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
